# Generated by Django 4.0.6 on 2022-07-15 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_isbn_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f8e36d3-22ec-4de3-a0aa-549f83b0d4d1'), help_text='ID único para este libro', primary_key=True, serialize=False),
        ),
    ]
