# Generated by Django 4.0.6 on 2022-08-11 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_options_bookinstance_borrower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6855fdc-cb43-41a3-aaf8-0b61712a9f0f'), help_text='ID único para este libro', primary_key=True, serialize=False),
        ),
    ]
